google:
  service: GCS
  project: cereal-killers
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: cereal-killers_bucket
google_dev:
  service: GCS
  project: cereal-killers
  credentials: <%= Rails.root.join("config/secrets/reviews_demo.json") %>
  bucket: cereal-killers_bucket