local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

google:
  service: GCS
  project: cereal-killers
  credentials: <%= ENV['GOOGLE_APPLICATION_CREDENTIALS'].as_json %>
  bucket: cereal-killers_bucket
  
google_dev:
  service: GCS
  project: cereal-killers
  credentials: <%= Rails.root.join("config/secrets/rare-hub-276523-20f195c7f9f8.json") %>
  bucket: cereal-killers_bucket